### ISSUE TITLE
Sorting will be a cool feature to have

### ISSUE THREAD

**Issue by waseemfa** [nmondal/njexl#1]
Having a single line sorting mechanism will be a cool feature to have.  Might be useful if you implement this.

**Comment by nmondal** [comment]
Implemented. Very good suggestion.

       (njexl)x = [ 2.0 , 1.0 , -0.9, -99.0 ]
       =>@[2.0, 1.0, -0.9, -99.0]
       (njexl)sorta(x)
      =>[-99.0, -0.9, 1.0, 2.0]
      (njexl)sortd(x)
      =>[2.0, 1.0, -0.9, -99.0]

And we have full anonymous function support as tested in test source.

**Comment by waseemfa** [comment]
Works fine !!

Thanks for this feature.
