### ISSUE TITLE
Correct `Installation Guide` wiki 

### ISSUE THREAD

**Issue by purijatin** [nmondal/njexl#10]
When specifying alias, there shouldn't be any empty space in between alias name and equal to sign. 
i.e. `alias njexl = ..` must be `alias njexl=...`.
Else it is read as a character.

Also added doc to reload the login file (makes it effortless for people who are not aware of it)

Changes to be done can be found here: https://github.com/purijatin/njexl_wiki/commit/d6f5468bc672d6fbb40a421a52c05c4e98caaa27

PS: Looks like in github, you cannot fork a wiki. Hence it is slightly difficult to send the pull request

**Comment by nmondal** [comment]
This has been fixed! Thanks!
