### ISSUE TITLE
Power function is not working when a variable is used

### ISSUE THREAD

**Issue by waseemfa** [nmondal/njexl#2]
Tried the power predicate.  Seems to be some issue there.  Please check.

**Comment by waseemfa** [comment]
When tried
100**2, this worked 
but
when tried the following
a=10
a**2, this doesn't work.

**Comment by nmondal** [comment]
This is fixed. Please close after testing.

       (njexl)10.1 ** 2
       =>102.00999999999999
      (njexl)x=10.1
      =>10.1
      (njexl)x ** 2
      =>102.00999999999999

Build and run, if not possible wait for next public build.

**Comment by waseemfa** [comment]
Tried and tested the issue.  Not reproducible any more.

Thanks,
Waseem
