### ISSUE TITLE
Iterate a map over key,value or key-value pair ?

### ISSUE THREAD

**Issue by japneet0212** [nmondal/njexl#4]
{for ( i  :  {0:'a' , 1:'b' , 2:'c' } )   write(i) }

This currently iterates over the values. 
Open point: Should the map be iterated over Key,Value or Key-Value Pair?

**Comment by nmondal** [comment]
Hence, the code excerpt is perfectly fine : 

    for ( p : { 0 :'a' , 1 : 'b' } ){
            write("%s -> %s\n", p.key , p.value         
    }

Will generate : 
         
    0 -> a
    1 -> b

**Comment by nmondal** [comment]
This is done now.
