### ISSUE TITLE
matrix.select not working

### ISSUE THREAD

**Issue by an-bansal** [nmondal/njexl#5]
(njexl)m.select{ $['Transaction Type'] == "TR001" }( 'Trasaction Type' )
Error : method invocation error : 'select' : at line 1, cols 3:65
Caused By : java.lang.Exception: No such header : Trasaction Type
(njexl)m.select{ write ( $['Transaction Type'] ) ; true }()

CSV File
-------------------
Transaction Type,Transaction Status,Buy Sell Indicator,Long Short Indicator,Position Type,Transaction Level,Client Trade Ref No.
TR001,COR,,,BL,A,TE381096BL
TR001,NEW,,,BL,A,TE381121BL
TR001,NEW,,,BL,A,TE381122BL
TR001,NEW,,,BL,A,TE381123BL
TR001,NEW,,,BL,A,TE381124BL
TR001,NEW,,,BL,A,TE381173BL
TR001,NEW,,,BL,A,TE381172BL
TR001,NEW,,,BL,A,TE381177BL
TR001,NEW,,,BL,A,TE381178BL

**Comment by nmondal** [comment]
This was an issue created by trailing "," in the end of line.
Apparently I did understand JDK spec wrong, so now fixed it.
This [checkin](https://github.com/nmondal/njexl/commit/1b517d1f82a82daaaa3f38c6099fa54b77305308) fixes it, 
please check and close.

**Comment by nmondal** [comment]
Fixed now.
